[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.135.3",
    "gitignore>=0.0.8",
    "langchain-core>=1.2.29",
    "langchain-google-genai>=4.2.1",
    "lxml>=6.0.4",
    "pymongo>=4.16.0",
    "python-dotenv>=1.2.2",
    "requests>=2.33.1",
    "tavily-python>=0.7.23",
    "uvicorn>=0.44.0",
]
